# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-12 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='doctor',
            name='home_phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_account_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='doctor',
            name='office_phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='doctor',
            name='suffix',
            field=models.CharField(default='', max_length=5),
        ),
    ]
