# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-12 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191212_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='drchrono_id',
            field=models.IntegerField(default=0),
        ),
    ]
