# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-12 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_doctor_drchrono_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.AddField(
            model_name='doctor',
            name='id',
            field=models.PositiveIntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
