# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-12 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191212_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='id',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='drchrono_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
