# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-12 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191212_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='suffix',
            field=models.CharField(default='', max_length=5, null=True),
        ),
    ]
