# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-12 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191212_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='group_npi_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='npi_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='timezone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
